<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StangaNetLib.ContentFlow.Tests</AssemblyName>
    <RootNamespace>StangaNetLib.ContentFlow.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <TargetFramework>net9.0</TargetFramework>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StangaNetLib.ContentFlow\StangaNetLib.ContentFlow.csproj" />
  </ItemGroup>
</Project>
